### ISSUE TITLE
Outdated CRS used

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/opengeohub2023#12]
> `crsuggest` suggests several CRS that are deprecated (outdated). I think you should prefer:

>    ETRF2000-PL / CS92 (EPSG: 2180) - CRS for the whole Poland (I use it in my materials),ETRF2000-PL / CS2000/18 (EPSG: 2177) - CRS for the 18 degree meridian.

Thanks @kadyb for the local geo knowledge : )

**Comment by kadyb** [comment]
Great!
