### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by agila5** [Robinlovelace/opengeohub2023#41]
Hi Robin! Some comments: 

1. https://github.com/Robinlovelace/opengeohub2023/blob/4ad8ad58447ba1fc839d6878b7caecf8b4970d37/osm.qmd#L36-L40

Did you add this part because of the issues that we had with layer/type or some other reasons? 

2. https://github.com/Robinlovelace/opengeohub2023/blob/4ad8ad58447ba1fc839d6878b7caecf8b4970d37/osm.qmd#L90

It should be "vignette" instead of "vignettte"

3. https://github.com/Robinlovelace/opengeohub2023/blob/4ad8ad58447ba1fc839d6878b7caecf8b4970d37/osm.qmd#L152

I think this sentence is a bit out of context and should be adjusted (since you never speak about Peru)

I checked until line 186, I'll check the rest later today!

**Comment by Robinlovelace** [comment]
Thanks Andrea, will take a look and act on these comments. More comments: v. welcome!

**Comment by Robinlovelace** [comment]
PR created https://github.com/Robinlovelace/opengeohub2023/pull/42

**Comment by agila5** [comment]
One more comment: it is oe_download_directory not oe_set_download_directory

https://github.com/Robinlovelace/opengeohub2023/blob/7e93773b58225557876601c7afd7934858c7fe60/osm.qmd#L247C67-L247C67

**Comment by Robinlovelace** [comment]
Thanks Andrea, will update accordingly..
