### ISSUE TITLE
Install rsgeo in workflow

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/opengeohub2023#6]
Heads-up @josiahParry I'm going to give this a go.

**Comment by JosiahParry** [comment]
Ah! Good luck. If you use r universe it should be just fine. But a heads up that I'm probably a week-ish away from finishing a group up rewrite (which will include the segmentize function!)

**Comment by Robinlovelace** [comment]
So far so good

![image](https://github.com/Robinlovelace/opengeohub2023/assets/1825120/3277fcf7-3359-40e9-a897-3fca50dc9184)


https://github.com/Robinlovelace/opengeohub2023/actions/runs/5968676706/job/16192977188

**Comment by JosiahParry** [comment]
Nice! it worked!
